# Generated by Django 5.2 on 2025-08-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_alter_profilemodel_options_profilemodel_birth_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='instagram',
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='information',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
