# Generated by Django 5.2 on 2025-08-27 20:11

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0005_remove_profilemodel_instagram_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='grade',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='graders',
            field=models.ManyToManyField(blank=True, related_name='my_graders', to=settings.AUTH_USER_MODEL),
        ),
    ]
