# Generated by Django 5.2 on 2025-08-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0006_profilemodel_grade_profilemodel_graders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='grade',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
