# Generated by Django 5.2 on 2025-08-27 21:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0007_alter_profilemodel_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='graders',
        ),
        migrations.CreateModel(
            name='GradeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='accounts_app.profilemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grade',
            },
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='score',
            field=models.ManyToManyField(related_name='user_score', through='accounts_app.GradeModel', to=settings.AUTH_USER_MODEL),
        ),
    ]
