# Generated by Django 5.2 on 2025-08-27 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0008_remove_profilemodel_grade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='score',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='grade',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='graders',
            field=models.ManyToManyField(blank=True, related_name='my_graders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GradeModel',
        ),
    ]
