# Generated by Django 5.2 on 2025-08-27 21:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0009_remove_profilemodel_score_profilemodel_grade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='graders',
        ),
        migrations.CreateModel(
            name='GradeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('grader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL)),
                ('target_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_grades', to='accounts_app.profilemodel')),
            ],
            options={
                'verbose_name': 'Grade',
                'unique_together': {('grader', 'target_profile')},
            },
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='total_score',
            field=models.ManyToManyField(blank=True, related_name='total_score', through='accounts_app.GradeModel', through_fields=('target_profile', 'grader'), to=settings.AUTH_USER_MODEL),
        ),
    ]
