# Generated by Django 5.2 on 2025-08-27 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0010_remove_profilemodel_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='total_score',
        ),
    ]
