# Generated by Django 5.2 on 2025-08-27 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0011_remove_profilemodel_total_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='total_score',
            field=models.ManyToManyField(blank=True, related_name='total_score', through='accounts_app.GradeModel', through_fields=('target_profile', 'grader'), to=settings.AUTH_USER_MODEL),
        ),
    ]
