# Generated by Django 5.2 on 2025-08-27 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0012_profilemodel_total_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='total_score',
            new_name='grade',
        ),
    ]
