# Generated by Django 5.2 on 2025-08-28 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0013_rename_total_score_profilemodel_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='grade',
        ),
    ]
