# Generated by Django 5.2 on 2025-08-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0014_remove_profilemodel_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('critic', 'Critic'), ('writer', 'Writer')], default='reader', max_length=6),
        ),
    ]
