# Generated by Django 5.2 on 2025-08-30 17:20

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0015_profilemodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='role',
            field=models.CharField(blank=True, choices=[('reader', 'Reader'), ('critic', 'Critic'), ('writer', 'Writer')], default='reader', max_length=6),
        ),
    ]
