# Generated by Django 5.2 on 2025-08-03 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_postmodel_published_at_alter_postmodel_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'verbose_name': 'Post'},
        ),
    ]
