# Generated by Django 5.2 on 2025-09-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_commentmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'verbose_name': 'Comment'},
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
