# Generated by Django 5.2 on 2025-08-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_postmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ['-published_at'], 'verbose_name': 'Post'},
        ),
    ]
