# Generated by Django 5.2 on 2025-09-04 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_commentmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReplyModel',
            fields=[
                ('commentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog_app.commentmodel')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='blog_app.commentmodel')),
            ],
            options={
                'verbose_name': 'Comment Reply',
                'verbose_name_plural': 'Comment Replies',
            },
            bases=('blog_app.commentmodel',),
        ),
    ]
