# Generated by Django 5.2 on 2025-09-05 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_commentreplymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentReplyModel',
        ),
    ]
