# Generated by Django 5.2 on 2025-08-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_postmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='slug',
            field=models.SlugField(),
        ),
    ]
