# Generated by Django 5.2 on 2025-09-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_commentreplymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreplymodel',
            name='target_comment',
        ),
        migrations.RemoveField(
            model_name='commentreplymodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentModel',
        ),
        migrations.DeleteModel(
            name='CommentReplyModel',
        ),
    ]
