# Generated by Django 5.2 on 2025-09-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_commentreplymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commentreplymodel',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
